### PR TITLE
[Fix] DataConverter improvements

### LINKED ISSUE #75: Accept `Temporal::DataConverter` in Client and Worker

### PR DESCRIPTION
**Pull request by antstorm**
## What was changed
This PR modifies `Client` and `Worker` interfaces to accept a single `DataConverter` as an argument instead of individual pieces(payload converter, codecs and failure converter).

It also includes a bug fix for the `DataConverter#to_payload` and `DataConverter#from_payload` to use codecs.

## Why?
This is one of the follow-ups to #74 

## Checklist

1. Closes 
#75 
#77 

2. How was this tested:
Specs and RBS updated

3. Any docs updates needed?
Inline documentation has been updated

### CODE REVIEW

File: lib/temporal/client.rb [hunk 1]
```diff
@@ -20,31 +20,18 @@ class Client
...
     # @see https://docs.temporal.io/concepts/what-is-a-data-converter for more information on
     #   payload converters and codecs.
     def initialize(
       connection,
       namespace,
       interceptors: [],
-      payload_converter: Temporal::PayloadConverter::DEFAULT,
-      payload_codecs: [],
-      failure_converter: Temporal::FailureConverter::DEFAULT
+      data_converter: Temporal::DataConverter.new
```
Comment (cretz) [inline lib/temporal/client.rb:32]:
```suggestion
      data_converter: Temporal::DataConverter::DEFAULT
```

Or something similar. Seems to make sense for consistency to have a default data converter and just reuse that like other converters (even though obviously there aren't hardly any perf gains).

**Review by cretz — APPROVED** [review]
LGTM. One minor suggestion.
