### PR TITLE
[Fix] Make Bridge Connection respond to Ruby interrupts

### LINKED ISSUE #95: Pass WorkerResult into Ruby land using `impl From<WorkerResult>`

### LINKED ISSUE #96: Make `Connection` interrupt friendly

### PR DESCRIPTION
**Pull request by antstorm**
## What was changed
This PR addresses the issue of Connection unable to respond to Ruby interrupts. This can happen when `Thread#raise` is called explicitly or when a Ruby program gets terminated with Ctrl+C mid execution (and falls into an outside of GVL blocking call).

The new implementation waits on a channel rather than a blocking `Runtime::block_on` and then returns an error when Ruby interrupt was requested.

## Why?
This is required to make sure our Client plays well with Activity cancellations and propagating fatal Core error on shutdown.

## Checklist

1. Closes #96 

2. Closes #95 

3. How was this tested:
Integration spec that exposes the issue added

4. Any docs updates needed?
No

### CODE REVIEW

File: bridge/src/lib.rs [hunk 1]
```diff
@@ -91,17 +92,21 @@ methods!(
...
                 request: request.clone(),
                 metadata: metadata.clone(),
                 timeout_millis: timeout
             };
-            connection.call(params)
-        }, Some(|| {}));
+            connection.call(params, tx.clone());
+            rx.recv().expect("RPC result channel closed")
+        }, Some(|| {
+            tx.send(Err(ConnectionError::RequestCancelled)).expect("Unable to close connection");
```
Comment (cretz) [inline bridge/src/lib.rs:108]: You can probably just `tokio::spawn` before the this thread start, and wait on it in the first lambda and https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html#method.abort in the second lambda.

Or you can use https://docs.rs/tokio-util/latest/tokio_util/sync/struct.CancellationToken.html. This is what I use in .NET.

File: spec/integration/client_spec.rb [hunk 2]
```diff
@@ -263,4 +263,29 @@ def terminate_workflow(input)
       expect(interceptor.results[5]).to eq([:terminate_workflow, handle.id])
     end
   end
+
+  # This case ensures we handle thread interruption (such as Thread#raise) properly
+  describe 'plays nice with GVL' do
```
Comment (cretz) [inline spec/integration/client_spec.rb:268]: When you get to activity tests, I would like to see a (platform specific) test that uses `Kernel#exec` to start a sleep for several seconds and confirm you can cancel it.

File: bridge/src/lib.rs [hunk 3]
```diff
@@ -91,17 +92,21 @@ methods!(
...
                 rpc: rpc.clone(),
                 request: request.clone(),
                 metadata: metadata.clone(),
                 timeout_millis: timeout
             };
-            connection.call(params)
-        }, Some(|| {}));
+            connection.call(params, tx.clone());
+            rx.recv().expect("RPC result channel closed")
+        }, Some(|| {
```
Comment (cretz) [inline bridge/src/lib.rs:107]: Question - how long will Ruby wait until "trying again" and/or segfaulting like you saw before?

File: bridge/src/lib.rs (hunk 1 above)
Comment (antstorm) [reply bridge/src/lib.rs]: Nice 👍 Implemented the change using `runtime.block_on` and a cancellation token.

I can't use `tokio::spawn` since I'm calling this from a non-async function and can't `.await`. But block_on works pretty much the same.

File: bridge/src/lib.rs (hunk 3 above)
Comment (antstorm) [reply bridge/src/lib.rs]: From what I've noticed sometimes it just hangs forever (waited for a minute and it was still hanging), but reliably segfaults on a second attempt to raise within than thread.

Comment (cretz) [reply bridge/src/lib.rs]: Can you replicate the segfault after this change? I just want to make sure we can never segfault, it scares me.

Comment (antstorm) [reply bridge/src/lib.rs]: Nope, what was reliably seg-faulting before won't seg-fault again

File: bridge/src/lib.rs [hunk 4]
```diff
@@ -91,17 +92,21 @@ methods!(
...
             let params = RpcParams {
                 rpc: rpc.clone(),
                 request: request.clone(),
                 metadata: metadata.clone(),
                 timeout_millis: timeout
             };
-            connection.call(params)
-        }, Some(|| {}));
+            connection.call(params, tx.clone());
+            rx.recv().expect("RPC result channel closed")
```
Comment (Sushisource) [inline bridge/src/lib.rs]: I wouldn't use `expect` in either spot here. You could blow up the whole process if any specific call has some weird interaction where either closure is dropped before the other one finishes its channel operation. I'd return some error instead which just fails the call.

It's not immediately clear to me when the unblock function is called. If that happens during interrupt, then this mostly makes sense, but I think the fact that the channel can be sent to by either the call or the interrupt is a bit weird feeling. Namely, the actual spawned call won't be interrupted, it'll just lose the channel race.

Using cancel token like Chad suggested fixes that problem. That way you only ever send down the channel from inside the call, and you select over either the token getting canceled or the call resolving.

Comment (Sushisource) [reply bridge/src/lib.rs]: Hah, this is all fixed while I was writing it!

Comment (antstorm) [reply bridge/src/lib.rs]: Yep, agree. I've also changed this to use cancellation token instead, but somehow you got the old version. Can you try refreshing the page?

**Review by Sushisource — APPROVED** [review]
Nice, lgtm

**Review by cretz — APPROVED** [review]
